# wekan  (trello clone)
#
# $ docker-compose up -d
#

wekan:
  image: wekanteam/wekan
  restart: always
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://localhost:80
  ports:
    - 80:8080
  networks:
    - wekannet

wekandb:
   image: mongo
   restart: always
   volumes:
     - ./db:/data/db
  networks:
    - wekannet

networks:
  wekannet:

